"""
Export utilities for generating downloadable reports.
Supports PDF and TXT export formats.
"""

import io
from datetime import datetime


def export_to_txt(content: str, title: str = "DocuMind AI Report") -> bytes:
    """
    Export content as a formatted plain text file.
    Returns bytes for download.
    """
    header = f"""{'='*60}
{title}
Generated by DocuMind AI
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{'='*60}

"""
    full_content = header + content
    return full_content.encode("utf-8")


def export_to_pdf(title: str, content: str) -> bytes:
    """
    Export content as a PDF file using reportlab.
    Falls back to HTML-based PDF if reportlab unavailable.
    Returns bytes for download.
    """
    try:
        return _export_with_reportlab(title, content)
    except ImportError:
        try:
            return _export_with_fpdf(title, content)
        except ImportError:
            raise RuntimeError(
                "PDF export requires 'reportlab' or 'fpdf2'. "
                "Install with: pip install reportlab"
            )


def _export_with_reportlab(title: str, content: str) -> bytes:
    """Generate PDF using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=inch * 0.75,
        leftMargin=inch * 0.75,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        spaceAfter=12,
        textColor=colors.HexColor("#6C63FF"),
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#4B44CC"),
        fontName="Helvetica-Bold",
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=16,
        spaceAfter=6,
        fontName="Helvetica",
        textColor=colors.HexColor("#2D2D2D"),
    )

    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888888"),
        alignment=TA_CENTER,
        spaceBefore=4,
    )

    story = []

    # Title
    story.append(Paragraph("🧠 DocuMind AI", title_style))
    story.append(Paragraph(title, heading_style))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        meta_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E0E0E0")))
    story.append(Spacer(1, 0.2 * inch))

    # Content - parse markdown-like formatting
    lines = content.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.1 * inch))
            continue

        if line.startswith("## "):
            story.append(Paragraph(line[3:], heading_style))
        elif line.startswith("### "):
            small_heading = ParagraphStyle(
                "SmallHeading", parent=heading_style,
                fontSize=12, textColor=colors.HexColor("#6C63FF")
            )
            story.append(Paragraph(line[4:], small_heading))
        elif line.startswith("**") and line.endswith("**"):
            bold_style = ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")
            story.append(Paragraph(line[2:-2], bold_style))
        elif line.startswith("- ") or line.startswith("• "):
            bullet_style = ParagraphStyle(
                "Bullet", parent=body_style,
                leftIndent=20, bulletIndent=10,
            )
            story.append(Paragraph(f"• {line[2:]}", bullet_style))
        elif line.startswith("#"):
            story.append(Paragraph(line.lstrip("#").strip(), heading_style))
        else:
            # Escape special XML characters
            safe_line = (line.replace("&", "&amp;").replace("<", "&lt;")
                         .replace(">", "&gt;"))
            story.append(Paragraph(safe_line, body_style))

    doc.build(story)
    return buf.getvalue()


def _export_with_fpdf(title: str, content: str) -> bytes:
    """Generate PDF using fpdf2 as fallback."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 12, "DocuMind AI", ln=True, align="C")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(75, 68, 204)
    pdf.cell(0, 10, title, ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, datetime.now().strftime("Generated: %B %d, %Y at %H:%M"), ln=True, align="C")
    pdf.ln(4)

    # Content
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(45, 45, 45)

    for line in content.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(3)
        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(108, 99, 255)
            pdf.cell(0, 8, line[3:], ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(45, 45, 45)
        elif line.startswith("- ") or line.startswith("• "):
            pdf.cell(6, 6, "•", ln=False)
            pdf.multi_cell(0, 6, line[2:])
        else:
            pdf.multi_cell(0, 6, line)

    return pdf.output()


def export_chat_to_html(chat_history: list) -> bytes:
    """Export chat history as a nicely formatted HTML file."""
    messages_html = ""
    for msg in chat_history:
        role = msg.get("role", "user")
        content = msg.get("content", "").replace("\n", "<br>")
        timestamp = msg.get("timestamp", "")[:16]
        citations = msg.get("citations", [])

        if role == "user":
            messages_html += f"""
            <div class="message user-message">
                <div class="role">You</div>
                <div class="content">{content}</div>
                <div class="time">{timestamp}</div>
            </div>"""
        else:
            cite_html = f'<div class="citations">📎 {", ".join(citations)}</div>' if citations else ""
            messages_html += f"""
            <div class="message ai-message">
                <div class="role">🧠 DocuMind AI</div>
                <div class="content">{content}</div>
                {cite_html}
                <div class="time">{timestamp}</div>
            </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DocuMind AI Chat Export</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0D0F1A; color: #F0F2FF; margin: 0; padding: 20px; }}
  h1 {{ color: #6C63FF; text-align: center; }}
  .message {{ max-width: 70%; margin: 12px 0; padding: 14px 18px; border-radius: 12px; }}
  .user-message {{ background: #4B44CC; margin-left: auto; border-radius: 12px 12px 4px 12px; }}
  .ai-message {{ background: #1E2035; border: 1px solid #2A2D45; border-radius: 12px 12px 12px 4px; }}
  .role {{ font-size: 11px; opacity: 0.7; margin-bottom: 6px; text-transform: uppercase; letter-spacing: 1px; }}
  .content {{ line-height: 1.7; }}
  .citations {{ margin-top: 8px; font-size: 12px; color: #9BA3CF; background: rgba(108,99,255,0.1); padding: 6px 10px; border-radius: 6px; }}
  .time {{ font-size: 11px; opacity: 0.5; margin-top: 6px; text-align: right; }}
</style>
</head>
<body>
<h1>🧠 DocuMind AI — Chat Export</h1>
<p style="text-align:center;color:#5C638A;">Exported: {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
<hr style="border-color:#2A2D45;margin:24px 0;">
{messages_html}
</body>
</html>"""

    return html.encode("utf-8")
